### ISSUE TITLE
Permanently disable logging

### ISSUE THREAD

**Issue by TerraTech** [miracle2k/stgit#1]
stgit-0.19

Is there a way to disable logging, either by an environment variable or a config option?  I looked through the source and couldn't find anything relevant.

I'd like to disable either by global or by repo.  If disabled globally, then one could override and enable by repo.

The reason I'd like to disable is it can clutter up the commit tree as I use the following quite a bit:
```sh
$ git log --graph --pretty=oneline --abbrev-commit --decorate --all --date-order
and
$ git log --abbrev-commit --all --boundary --branches --date-order --decorate --graph --oneline --pretty=oneline --simplify-by-decoration --topo-order
```
Thank you.

**Comment by TerraTech** [comment]
Question redirected to: https://github.com/ctmarinas/stgit/issues/32

**Comment by miracle2k** [comment]
Sorry, I don't even remember what stgit is or why I have this repo here, I am not going to accept any PRs :)
